apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-api.fullname" . }}
  labels:
    {{- include "users-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "users-api.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "users-api.selectorLabels" . | nindent 8 }}
        app: {{ include "users-api.name" . }}
    spec:
      serviceAccountName: {{ include "users-api.fullname" . }}
      containers:
        - name: users-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "users-api.fullname" . }}-config
            - secretRef:
                name: {{ include "users-api.fullname" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.service.targetPort }}
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            periodSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]