{{- if and .Values.keda.enabled .Values.keda.http.enabled }}
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: {{ include "users-api.fullname" . }}
  labels:
    {{- include "users-api.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.keda.http.hosts }}
    - {{ . | quote }}
    {{- end }}
  scaleTargetRef:
    name: {{ include "users-api.fullname" . }}
    service: {{ include "users-api.fullname" . }}
    port: {{ .Values.service.port }}
  replicas:
    min: {{ .Values.keda.minReplicaCount }}
    max: {{ .Values.keda.maxReplicaCount }}
  {{- with .Values.keda.cooldownPeriod }}
  scaledownPeriod: {{ . }}
  {{- end }}
  scalingMetric:
    requestRate:
      targetValue: {{ .Values.keda.http.targetRate }}
      window: {{ .Values.keda.http.window | default "1m" }}
      granularity: {{ .Values.keda.http.granularity | default "1s" }}
{{- end }}
