apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-gateway
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: demo-gateway
  policyTypes: [Ingress]
  ingress:
    - ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
