apiVersion: v1
kind: Service
metadata:
  name: notify-api
  labels:
    app: notify-api
spec:
  type: ClusterIP
  selector:
    app: notify-api
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
