# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
mode: deployment

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

image:
  repository: otel/opentelemetry-collector-contrib   # contrib has more receivers/exporters

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  processors:
    batch: {}
  exporters:
    debug:
      verbosity: detailed
    otlp/tempo:
      endpoint: tempo.lgtm.svc:4317
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers:  [otlp]
        processors: [batch]
        exporters:  [otlp/tempo, debug]