apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/mabhi256/k8s-learn.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: "2.*"
      helm:
        valueFiles:
          - $values/helm/values/keda.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-http
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/mabhi256/k8s-learn.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://kedacore.github.io/charts
      chart: keda-add-ons-http
      targetRevision: "0.*"
      helm:
        valueFiles:
          - $values/helm/values/keda-http.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true