apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-api
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: users-api-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: users-api/DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: users-api/DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: lgtm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin-password
