apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store
  namespace: default
spec:
  provider:
    fake:
      data:
        - key: users-api/DB_USER
          value: "appuser"
        - key: users-api/DB_PASSWORD
          value: "secret"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store
  namespace: lgtm
spec:
  provider:
    fake:
      data:
        - key: grafana/admin-user
          value: "admin"
        - key: grafana/admin-password
          value: "supersecret"
