image:
  repository: users-api
  tag: local-v3
  pullPolicy: Never

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# resources:
#   requests:
#     cpu: 100m
#     memory: 128Mi
#   limits:
#     cpu: 200m
#     memory: 256Mi

# can also write like this
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70
  customMetric:
    enabled: true
    name: http_requests_per_second
    targetAverageValue: "10"

env:
  LOG_LEVEL: "debug"
  NOTIFY_HOST: notify-api
  NOTIFY_PORT: "50051"
  DB_HOST: postgres-pooler-rw
  DB_PORT: "5432"
  DB_NAME: appdb
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.lgtm.svc:4317"
  OTEL_SERVICE_NAME: "users-api"

secrets:
  DB_USER: "appuser"
  DB_PASSWORD: "secret"

serviceMonitor:
  enabled: true
  namespace: lgtm

vpa:
  enabled: true
  updateMode: InPlaceOrRecreate
  minAllowed:
    cpu: 25m
    memory: 64Mi
  maxAllowed:
    cpu: 500m
    memory: 512Mi
  controlledResources:
    - cpu
    - memory

version: v1

canary:
  enabled: false
  version: v2
  replicaCount: 1
  image:
    repository: users-api
    tag: local-v3
    pullPolicy: Never

istio:
  peerAuthentication:
    enabled: false
    mode: STRICT
  destinationRule:
    enabled: false
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  virtualService:
    enabled: false
    stableWeight: 95
    canaryWeight: 5
    retries:
      attempts: 2
      retryOn: 5xx
    timeout: 5s

keda:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 300
  pollingInterval: 15
  prometheus:
    serverAddress: http://prom-kube-prometheus-stack-prometheus.lgtm.svc:9090
    query: sum(rate(http_requests_total{namespace="default",service="users-api"}[2m]))
    threshold: "10"
    activationThreshold: "1"
  cron:
    enabled: false
    timezone: "UTC"
    start: "0 8 * * 1-5"
    end: "0 18 * * 1-5"
    desiredReplicas: "3"

migrate:
  enabled: true

nameOverride: ""
fullnameOverride: ""