apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: demo-gateway
  namespace: default
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: demo.local
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      hostname: demo.local
      tls:
        mode: Terminate
        certificateRefs:
          - name: demo-local-tls
      allowedRoutes:
        namespaces:
          from: Same