apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-credentials
  namespace: default
type: kubernetes.io/basic-auth

# can use both stringData and data
# stringData:
#   username: appuser
#   password: secret

# base64 encoded stringData
data:
  username: YXBwdXNlcg==
  password: c2VjcmV0