apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notify-api.fullname" . }}
  labels:
    {{- include "notify-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notify-api.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "notify-api.selectorLabels" . | nindent 8 }}
        app: {{ include "notify-api.name" . }}
    spec:
      serviceAccountName: {{ include "notify-api.fullname" . }}
      containers:
        - name: notify-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 50051
            - containerPort: 9091
              name: metrics
          envFrom:
            - configMapRef:
                name: {{ include "notify-api.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: 50051
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 50051
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 50051
            periodSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
