{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notify-api.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "notify-api.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      {{- include "notify-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_version]
          targetLabel: version
{{- end }}
