apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: postgres-app-credentials

  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'

  storage:
    size: 1Gi

  postgresql:
    parameters:
      shared_buffers: "128MB"
      max_connections: "100"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
