apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.com/mabhi256/k8s-learn.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "7.*"
      helm:
        valueFiles:
          - $values/helm/values/loki.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
