apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: users-api-restarter
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["users-api"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-restarter
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ci
    namespace: default
roleRef:
  kind: Role
  name: users-api-restarter
  apiGroup: rbac.authorization.k8s.io
