apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  labels:
    app: users-api

data:
  LOG_LEVEL: "debug"
  NOTIFY_HOST: "notify-api"
  NOTIFY_PORT: "50051"
  DB_HOST: "postgres-rw"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.lgtm.svc:4317"
  OTEL_SERVICE_NAME: "users-api"