apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-v2
  labels:
    # Labels the Deployment object. kubectl get deploy -l app=users-api
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      # Defines which Pods belong to this Deployment
      app: users-api
      version: v2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        # Labels assigned to created pods. 
        # kubectl get pods -l app=users-api,version=v2 shows only v2 pods
        # kubectl get pods -l app=users-api will show both v1 and v2
        app: users-api
        version: v2
    spec:
      serviceAccountName: users-api
      containers:
        - name: users-api
          image: users-api:local-v3
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: users-api-config
            - secretRef:
                name: users-api-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /live
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            periodSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]