apiVersion: v1
kind: Secret
metadata:
  name: users-api-secret
  labels:
    app: users-api
type: Opaque
data:
  DB_USER: YXBwdXNlcg==
  DB_PASSWORD: c2VjcmV0
  DATABASE_URL: cG9zdGdyZXNxbDovL2FwcHVzZXI6c2VjcmV0QHBvc3RncmVzLXJ3OjU0MzIvYXBwZGI=