apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: users-api
  namespace: lgtm
  labels:
    app.kubernetes.io/name: users-api
    app.kubernetes.io/instance: users-api
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: users-api
      app.kubernetes.io/instance: users-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
